### ISSUE TITLE
invalid literal

### ISSUE THREAD

**Issue by Boomw0351** [ismailhammounou/db2ixf#72]
![image](https://github.com/ismailhammounou/db2ixf/assets/62632397/eaec9675-b85b-4194-84b5-b9d3349fd65d)
hello  
this ixf file can read by Tribometer Demo 8.0.19 ，which is software about material  
but  everytime i try ， always this question

**Comment by ismailhammounou** [comment]
Hi @Boomw0351 ,

Thank you for your feedback. Can you, please, provide more context ? 

What is the version of the database you used to get the IXF file ? Are you sure the file is not corrupted ? Does It contain non Arabic numbers (self.table_info['IXFCCNT'] contains an integer as a character) ? What is the output format you want to get (csv, json, jsonline, parquet, deltalake) ?  

self.table_info['IXFCCNT'] contains the number of columns in the table and it is an integer, the error means that int() failed to parse the characters as an integer. Therefore, I have doubts about the file, either it is not an IBM IXF file or it is a corrupted file or it contains non arabic numbers; It can also be a bug but I can not say that until I get more context. 

Thank you, 
BR,
Ismail

**Comment by ismailhammounou** [comment]
Hi @Boomw0351 ,

Do you have any updates ? 

Thank you,
BR,
Ismail

**Comment by ismailhammounou** [comment]
Hi @Boomw0351,

I suppose your problem was resolved. I will close the ticket. Please, feel free to reopen an new one in case you face issues.

Best Regards,
Ismail
